In [1]:
%pylab inline 
import pandas as pd
import numpy as np
from scipy import interpolate

Populating the interactive namespace from numpy and matplotlib


In [3]:
prob = np.load("prob.npy")
prob

array([0.98828207, 0.986881  , 0.98568157, 0.98477179, 0.98408444,
       0.98346398, 0.98280699, 0.98214304, 0.98144266, 0.98070591,
       0.97995497, 0.97921927, 0.97847673, 0.97772003, 0.97696388,
       0.97609828, 0.97513816, 0.97418624, 0.97324249, 0.97224116,
       0.97106564, 0.96963635, 0.96793982, 0.96591924, 0.96354757,
       0.9608778 , 0.95785464, 0.95435201, 0.95031767, 0.94577225,
       0.94083612, 0.93553634, 0.9297738 , 0.92353596, 0.91685984,
       0.90969997, 0.90218345, 0.89454917, 0.88689476, 0.87906873,
       0.87050953, 0.86129715, 0.85202726, 0.84281219, 0.83325994,
       0.82248918, 0.8102755 , 0.79702273, 0.78268864, 0.76694275,
       0.74895781, 0.72875588, 0.70698773, 0.68374187, 0.6586057 ,
       0.6303344 , 0.59924801, 0.56669902, 0.53306456, 0.49787087,
       0.45973063, 0.41937498, 0.37879578, 0.33867486, 0.29885913,
       0.25929479, 0.22041799, 0.18307063, 0.14827566, 0.11698081,
       0.        ])

In [3]:
det = np.load("detEarning.npy")
det

array([ 35.        ,  37.16666667,  39.33333333,  41.5       ,
        43.66666667,  45.83333333,  48.        ,  50.16666667,
        52.33333333,  54.5       ,  56.66666667,  58.83333333,
        61.        ,  63.16666667,  65.33333333,  67.5       ,
        69.66666667,  71.83333333,  74.        ,  76.16666667,
        78.33333333,  80.5       ,  82.66666667,  84.83333333,
        87.        ,  89.16666667,  91.33333333,  93.5       ,
        95.66666667,  97.83333333, 100.        ,  97.        ,
        94.        ,  91.        ,  88.        ,  85.        ,
        82.        ,  79.        ,  76.        ,  73.        ,
        70.        ,  63.        ,  56.        ,  49.        ,
        42.        ,  35.        ,  35.        ,  35.        ,
        35.        ,  35.        ,  35.        ,  35.        ,
        35.        ,  35.        ,  35.        ,  35.        ,
        35.        ,  35.        ,  35.        ,  35.        ,
        35.        ,  35.        ,  35.        ,  35.  

In [17]:
import numpy as np
import pandas as pd
import xarray as xr
from scipy.interpolate import RectBivariateSpline as RS

In [4]:
da = xr.DataArray(np.sin(0.3 * np.arange(12).reshape(4, 3)), [('time', np.arange(4)), ('space', [0.1, 0.2, 0.3])])

In [5]:
da

<xarray.DataArray (time: 4, space: 3)>
array([[ 0.        ,  0.29552021,  0.56464247],
       [ 0.78332691,  0.93203909,  0.99749499],
       [ 0.97384763,  0.86320937,  0.67546318],
       [ 0.42737988,  0.14112001, -0.15774569]])
Coordinates:
  * time     (time) int64 0 1 2 3
  * space    (space) float64 0.1 0.2 0.3

In [6]:
np.sin(0.3 * np.arange(12).reshape(4, 3))

array([[ 0.        ,  0.29552021,  0.56464247],
       [ 0.78332691,  0.93203909,  0.99749499],
       [ 0.97384763,  0.86320937,  0.67546318],
       [ 0.42737988,  0.14112001, -0.15774569]])

In [8]:
vgrid = np.load("Vgrid.npy")

In [14]:
vgrid[:,:,1,1,1,70]

array([[1.71671388, 1.80924108, 1.87355351, ..., 1.9997798 , 1.99979237,
        1.999804  ],
       [1.77751047, 1.83888671, 1.88729953, ..., 1.99977984, 1.99979241,
        1.99980404],
       [1.8276844 , 1.86694208, 1.90178543, ..., 1.99977991, 1.99979246,
        1.99980409],
       ...,
       [1.99989406, 1.99989408, 1.99989411, ..., 1.99992845, 1.99992983,
        1.99993121],
       [1.9998971 , 1.99989711, 1.99989714, ..., 1.99992985, 1.99993118,
        1.99993251],
       [1.99990002, 1.99990004, 1.99990006, ..., 1.99993122, 1.9999325 ,
        1.99993378]])

In [15]:
# wealth discretization 
w_grid_size = 100
w_lower = 3
w_upper = 20000
# 401k amount discretization 
n_grid_size = 50
n_lower = 3
n_upper = 10000

def powspace(start, stop, power, num):
    start = np.power(start, 1/float(power))
    stop = np.power(stop, 1/float(power))
    return np.power(np.linspace(start, stop, num=num), power)
ws = powspace(w_lower, w_upper, 3, w_grid_size)
ns = powspace(n_lower, n_upper, 3, n_grid_size)

In [55]:
da = xr.DataArray(vgrid[:,:,1,1,1,70], [('wealth', ws), ('rFund', ns)])

In [56]:
rsInter = RS(ws, ns, vgrid[:,:,1,1,1,70])

In [57]:
%timeit rsInter.ev(np.linspace(1,10000,10000),np.linspace(1,10000,10000))

3.71 ms ± 572 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [59]:
%timeit da.interp(wealth = np.linspace(1,10000,100), rFund = np.linspace(1,10000,100))

9.47 ms ± 668 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [64]:
da.interp(wealth = np.linspace(5,1000,100), rFund = np.linspace(5,1000,100))

ValueError: fill_value must be either 'None' or of a type compatible with values