In [1]:
import numpy as np
earning = np.load("detEarning.npy")

In [ ]:
earning

In [2]:
earning

array([ 35.        ,  37.16666667,  39.33333333,  41.5       ,
        43.66666667,  45.83333333,  48.        ,  50.16666667,
        52.33333333,  54.5       ,  56.66666667,  58.83333333,
        61.        ,  63.16666667,  65.33333333,  67.5       ,
        69.66666667,  71.83333333,  74.        ,  76.16666667,
        78.33333333,  80.5       ,  82.66666667,  84.83333333,
        87.        ,  89.16666667,  91.33333333,  93.5       ,
        95.66666667,  97.83333333, 100.        ,  97.        ,
        94.        ,  91.        ,  88.        ,  85.        ,
        82.        ,  79.        ,  76.        ,  73.        ,
        70.        ,  63.        ,  56.        ,  49.        ,
        42.        ,  35.        ,  35.        ,  35.        ,
        35.        ,  35.        ,  35.        ,  35.        ,
        35.        ,  35.        ,  35.        ,  35.        ,
        35.        ,  35.        ,  35.        ,  35.        ,
        35.        ,  35.        ,  35.        ,  35.  

In [6]:
np.where(earning == 100)

(array([30]),)

In [7]:
np.where(earning == 70)

(array([40]),)